import './globals.css'
import type { Metadata } from 'next'
import { Khula } from 'next/font/google'

const khula = Khula({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={khula.className}>{children}</body>
    </html>
  )
}
